/* ===========================================================================
 * deskmatch — server side of the desk-selection web app.
 *
 * Read docs/SPEC.md first. In particular:
 *   §2.2  the eligibility rule table and its predicate grammar
 *   §3.1  the response CSV columns this file appends to the Sheet
 *   §3.3  roster-vs-submission conflict resolution
 *
 * Two rules govern everything in this file.
 *
 *   1. NOTHING about the size of the problem is written down here. The number
 *      of desks, rooms, zones, people and K are all read from ConfigData.gs at
 *      runtime (K = length of the primary scoring curve). If you find yourself
 *      typing a number that means "how many of something", stop.
 *
 *   2. The client is not trusted. Every rule the browser enforces is enforced
 *      again in submitRanking(). The browser decides what is *easy* to do; this
 *      file decides what is *possible*.
 *
 * All problem data comes from ConfigData.gs, which is generated by
 * tools/sync_config.py from config/. Never hand-edit ConfigData.gs.
 *
 * Script properties you must set before the form opens (Project Settings ->
 * Script Properties). See frontend/DEPLOY.md.
 *
 *   RESPONSE_SHEET_NAME     required. Tab name to append responses to.
 *   RESPONSE_SPREADSHEET_ID optional. Spreadsheet to write to. Omit only if
 *                           this script is bound to the spreadsheet itself.
 *   DEADLINE_ISO            optional. ISO-8601 instant after which submissions
 *                           are refused, e.g. 2026-09-15T23:59:59-04:00.
 *   ALLOW_PROXY_SUBMIT      optional. "true" lets a signed-in user submit under
 *                           a different roster email (coordinator taking a
 *                           submission over the phone). Off by default.
 *   PRELOCK_ENABLED         optional. WHICH PHASE THE CYCLE IS IN. The two are
 *                           mutually exclusive and this one property switches
 *                           between them:
 *                             "true"  -> PHASE 1, keeping seats. A student may
 *                                        claim the desk they already sit at.
 *                                        Ranking is CLOSED: submitRanking()
 *                                        refuses, and the client greys Choose
 *                                        and Confirm out.
 *                             "false" -> PHASE 2, ranking (the default). The
 *                                        pre-lock step is greyed out and
 *                                        unreachable, and everyone ranks.
 *                           Ranking is refused in phase 1 because the roster
 *                           has not yet been updated with the keepers, so a
 *                           ranking submitted then would be computed against a
 *                           stale pool. Run phase 1, close it, merge the
 *                           keepers into config/roster.csv, re-sync, then flip
 *                           this to "false" — frontend/DEPLOY.md step 5b.
 *                           Claims made in phase 1 stay enforced in phase 2.
 *   PRELOCK_DEADLINE_ISO    optional. ISO-8601 instant after which claims are
 *                           refused. Independent of DEADLINE_ISO, and usually
 *                           earlier — the coordinator wants the keepers settled
 *                           before everyone else ranks. It is also what the
 *                           form quotes to a phase-1 student who wants to move
 *                           and is told when ranking opens. DEADLINE_ISO still
 *                           applies as the outer bound.
 *   KEEPERS_SHEET_NAME      optional. Tab the pre-lock claims are appended to.
 *                           Defaults to "Keepers".
 *   ACCOMMODATIONS_SHEET_NAME
 *                           optional. Tab the private notes to the coordinator
 *                           are appended to. Defaults to "Accommodations".
 *                           That tab is CONFIDENTIAL — see section 6b.
 * ======================================================================== */

var APP_NAME = 'deskmatch';
var APP_BUILD = '1.1.0';

var PROP_SHEET_NAME = 'RESPONSE_SHEET_NAME';
var PROP_SPREADSHEET_ID = 'RESPONSE_SPREADSHEET_ID';
var PROP_DEADLINE_ISO = 'DEADLINE_ISO';
var PROP_ALLOW_PROXY = 'ALLOW_PROXY_SUBMIT';
var PROP_PRELOCK_ENABLED = 'PRELOCK_ENABLED';
var PROP_PRELOCK_DEADLINE_ISO = 'PRELOCK_DEADLINE_ISO';
var PROP_KEEPERS_SHEET_NAME = 'KEEPERS_SHEET_NAME';
var PROP_ACCOMMODATIONS_SHEET_NAME = 'ACCOMMODATIONS_SHEET_NAME';

var DEFAULT_KEEPERS_SHEET = 'Keepers';
var DEFAULT_ACCOMMODATIONS_SHEET = 'Accommodations';

/* The fixed part of the response header (SPEC §3.1). The choice_N columns are
 * generated from K and spliced in between these two halves.
 *
 * `year` is deliberately absent: the form no longer asks for it, because
 * candidacy alone decides which zones a person may sit in. */
var HEADER_LEAD = ['submission_id', 'timestamp', 'email', 'name', 'candidacy'];
var HEADER_TAIL = ['client_version', 'auth_method'];

/* The pre-lock claim log. Append-only, exactly like the response sheet:
 * releasing a desk writes a new row with keeping=false, and the latest row per
 * email wins. tools/merge_keepers.py folds this into config/roster.csv. */
var KEEPERS_HEADER = ['claim_id', 'timestamp', 'email', 'name', 'desk_id',
                      'keeping', 'client_version'];

/* The private-note log (section 6b). A SEPARATE tab, deliberately: these notes
 * are confidential and the response sheet is the file that gets exported,
 * hashed, anonymised and published. Nothing here is ever written to a response
 * row, and the solver never reads this tab. */
var ACCOMMODATIONS_HEADER = ['note_id', 'timestamp', 'email', 'name', 'note',
                             'client_version'];

/* How much a student may write in one note. Not a dimension of the problem —
 * it is a UI/storage limit — but it is written down once, here, and the client
 * is told what it is by getBootstrap() rather than repeating the number. */
var ACCOMMODATION_MAX_CHARS = 1500;

var AUTH_GOOGLE = 'google';
var AUTH_SELF_SELECT = 'self_select';

var LOCK_TIMEOUT_MS = 30000;

/* ===========================================================================
 * 1. Web app entry points
 * ======================================================================== */

/**
 * Serves the single-page app.
 *
 * Validates nothing — it must render even when the config is broken, the Sheet
 * is unreachable or the visitor cannot be identified, because a blank page
 * tells the student nothing. Every failure mode is reported by getBootstrap()
 * as data the client can display.
 *
 * @param {Object} e Apps Script request object (unused; kept for the signature).
 * @return {HtmlOutput}
 */
function doGet(e) {                                        // eslint-disable-line no-unused-vars
  var template = HtmlService.createTemplateFromFile('Index');
  // Available to Index.html as <?= clientVersion ?> if a view wants to show it.
  template.clientVersion = clientVersion_();
  return template
    .evaluate()
    .setTitle('Desk selection — U-M Astronomy')
    .addMetaTag('viewport', 'width=device-width, initial-scale=1')
    .setXFrameOptionsMode(HtmlService.XFrameOptionsMode.ALLOWALL);
}

/**
 * Standard Apps Script partial include: <?!= include('Style') ?>.
 *
 * @param {string} name File name without the .html extension.
 * @return {string} Raw file contents, inlined into the parent template.
 */
function include(name) {
  return HtmlService.createHtmlOutputFromFile(name).getContent();
}

/* ===========================================================================
 * 2. Bootstrap — everything the client needs in one round trip
 * ======================================================================== */

/**
 * Builds the whole client-side world in one call: config, identity, locked
 * desks, the student's previous submission and the live first-choice counts.
 *
 * Never throws. Anything that can fail independently (identity lookup, Sheet
 * access, one person's eligibility) is caught and degraded: the caller gets
 * `ok: true` plus a `warnings` array, or `ok: false` plus `error` if the config
 * itself is unusable. A missing Google identity is normal, not an error — it
 * puts the client into the self-select fallback.
 *
 * @return {Object} See the shared client contract in the repo README/DEPLOY.
 */
function getBootstrap() {
  var warnings = [];
  var rooms, scoring, curve, k, zones, roster;

  try {
    rooms = cfg_('ROOMS_JSON');
    scoring = cfg_('SCORING_JSON');
    curve = primaryCurve_();
    k = curve.length;
    zones = rooms.zones || {};
    roster = rosterRows_();
  } catch (err) {
    // The config is unusable. Say so plainly rather than rendering a form that
    // cannot possibly work.
    return {
      ok: false,
      error: errText_(err),
      k: 0,
      curve: [],
      seedString: '',
      deadlineIso: null,
      deadlinePassed: false,
      clientVersion: clientVersion_(),
      rooms: null,
      zones: {},
      person: null,
      identity: { sessionEmail: '', onRoster: false },
      rosterNames: [],
      lockedDesks: [],
      allowedZonesFor: {},
      priorSubmission: null,
      priorAccommodation: null,
      accommodationMaxChars: ACCOMMODATION_MAX_CHARS,
      concentration: {},
      // Consistent with prelock.enabled below it. The client never gets this
      // far — ok:false stops it at the boot screen — but the two must not
      // contradict each other for anyone reading the payload.
      phase: PHASE_RANKING,
      prelock: { enabled: false, deadlineIso: null, deadlinePassed: false },
      claims: [],
      myClaim: null,
      warnings: warnings
    };
  }

  // ---- identity ---------------------------------------------------------
  // Session.getActiveUser().getEmail() returns '' for anyone outside the
  // deploying domain, and throws in some sharing configurations. Both are
  // handled: we fall back to self-select and record that in auth_method.
  var sessionEmail = activeEmail_();
  var matched = sessionEmail ? findRosterRow_(roster, sessionEmail) : null;
  if (sessionEmail && !matched) {
    warnings.push(
      'You are signed in as ' + sessionEmail + ', which is not on the roster. ' +
      'Pick your name from the list, or ask the coordinator to add you.'
    );
  }

  var person = null;
  if (matched) {
    var decision = safeDecision_(matched.attributes);
    person = {
      email: matched.email,
      name: matched.name,
      year: matched.year,
      candidacy: matched.candidacy,
      keepsDesk: matched.keepsDesk,
      currentDesk: matched.currentDesk,
      allowedZones: decision.zones,
      eligibilityRuleId: decision.ruleId,
      eligibilityReason: decision.reason,
      authMethod: AUTH_GOOGLE
    };
    if (decision.error) {
      person.eligibilityError = decision.error;
      warnings.push('Could not work out which desks you are eligible for: ' + decision.error);
    }
  }

  // ---- per-person eligibility, for the self-select dropdown -------------
  var allowedZonesFor = {};
  var rosterNames = [];
  for (var i = 0; i < roster.length; i++) {
    var row = roster[i];
    var d = safeDecision_(row.attributes);
    allowedZonesFor[row.email] = d.zones;
    rosterNames.push({
      email: row.email,
      name: row.name,
      year: row.year,
      candidacy: row.candidacy,
      keepsDesk: row.keepsDesk          // the client greys these out; the server refuses them
    });
  }

  // ---- Sheet-derived data (optional; the form still works without it) ---
  var priorSubmission = null;
  var concentration = {};
  try {
    var responses = readResponses_();
    concentration = firstChoiceCounts_(responses);
    var who = person ? person.email : '';
    if (who && responses.latest[who]) {
      priorSubmission = {
        choices: responses.latest[who].choices,
        timestampIso: responses.latest[who].timestampIso
      };
    }
  } catch (err2) {
    warnings.push('Previous submissions could not be read: ' + errText_(err2));
  }

  // ---- the private note from their last submission ----------------------
  // Sent back ONLY to a person Google has identified as themselves: `person`
  // is non-null only when the session email matched a roster row, so a
  // self-selected visitor is never handed anybody's note — not even their own.
  // Without this the box would look empty on a re-visit and re-ranking would
  // silently drop a note the coordinator had already been told about.
  var priorAccommodation = null;
  if (person) {
    try {
      var mineNote = latestAccommodationFor_(person.email);
      if (mineNote) {
        priorAccommodation = { note: mineNote.note, timestampIso: mineNote.timestampIso };
      }
    } catch (err4) {
      warnings.push('Your private note to the coordinator could not be read, so the box on ' +
        'the last page may look empty even though a note is on file. Anything you write ' +
        'there now will replace it: ' + errText_(err4));
    }
  }

  // ---- pre-lock claims --------------------------------------------------
  // Only read while the step is switched on. When the coordinator turns it off
  // the step is not in use this year, and nothing else about the form changes
  // — including which desks are shown as taken.
  var prelock = prelockSettings_();
  var claims = [];
  var myClaim = null;
  // Claims are read ALWAYS, not only while the step is switched on.
  //
  // PRELOCK_ENABLED means "students may still claim a desk", not "claims
  // exist". If reading them were gated on the switch, turning the step off
  // after people had claimed would silently un-hold their desks: the form would
  // start offering those desks to everyone, and a student who was told "there
  // is nothing else for you to do" could lose their seat without ever being
  // asked. That failure is invisible to the coordinator and lands on the one
  // person who did what the form told them to.
  //
  // submitRanking() reads them unconditionally for the same reason, so the two
  // always agree and the form can never invite a ranking the server will refuse.
  {
    try {
      claims = activeClaims_(roster);
      var mine = person ? person.email : '';
      for (var c = 0; c < claims.length; c++) {
        if (mine && claims[c].email === mine) { myClaim = claims[c]; break; }
      }
    } catch (err3) {
      warnings.push('The pre-lock claims could not be read, so desks other people ' +
        'have already claimed may not be shown as taken: ' + errText_(err3));
    }
  }

  // ---- deadline ---------------------------------------------------------
  var deadline = deadline_();

  return {
    ok: true,
    k: k,
    curve: curve,
    seedString: scoring.tie_break_seed || '',
    seedCommittedAt: scoring.seed_committed_at || null,
    deadlineIso: deadline.iso,
    deadlinePassed: deadline.passed,
    clientVersion: clientVersion_(),
    configFingerprint: safeCfg_('CONFIG_FINGERPRINT', ''),
    rooms: rooms,                                  // rooms.json, verbatim
    zones: zones,
    person: person,
    identity: { sessionEmail: sessionEmail, onRoster: !!matched },
    rosterNames: rosterNames,
    lockedDesks: lockedDesks_(roster),
    allowedZonesFor: allowedZonesFor,
    priorSubmission: priorSubmission,
    priorAccommodation: priorAccommodation,        // this person's own, or null
    accommodationMaxChars: ACCOMMODATION_MAX_CHARS,
    concentration: concentration,
    // Which phase the cycle is in, said outright rather than left for the
    // client to infer from prelock.enabled. 'prelock' means Choose and Confirm
    // are shut and submitRanking() will refuse; 'ranking' means the pre-lock
    // step is shut and claimDesk() will refuse.
    phase: phase_(),
    prelock: {
      enabled: prelock.enabled,
      deadlineIso: prelock.deadlineIso,
      deadlinePassed: prelock.deadlinePassed
    },
    claims: claims,                                // every desk claimed and kept
    myClaim: myClaim,                              // this person's, or null
    warnings: warnings
  };
}

/**
 * Live first-choice counts, so the select view can refresh the "everyone is
 * picking the same desk" warning without re-fetching the whole bootstrap.
 *
 * Validates nothing. Returns {} if the Sheet cannot be read.
 *
 * @return {Object} desk id -> number of people whose current top choice it is.
 */
function getConcentration() {
  try {
    return firstChoiceCounts_(readResponses_());
  } catch (err) {
    return {};
  }
}

/**
 * Recomputes allowed zones when the student corrects their candidacy on the
 * identity screen.
 *
 * Candidacy is the only thing the form asks them to confirm, because it is the
 * only thing that decides where they may sit. The year is not collected at all.
 *
 * Applies exactly the rule submitRanking() applies: the intersection of the
 * zones the roster entitles them to and the zones their claimed attributes
 * entitle them to, so the form can never offer a desk the server would reject.
 *
 * @param {Object} claim {email, candidacy}.
 * @return {Object} {ok, zones, rosterZones, claimZones, reason} | {ok:false, error}.
 */
function getEligibleZonesForClaim(claim) {
  claim = claim || {};
  try {
    var roster = rosterRows_();
    var row = findRosterRow_(roster, normEmail_(claim.email));
    if (!row) {
      return { ok: false, error: 'That email address is not on the roster.', zones: [] };
    }
    // The submitted candidacy governs; see the note in submitRanking(). This
    // must agree with the submit path exactly, or the form shows one set of
    // zones and the server enforces another.
    var rosterZones = getEligibleZones(row.attributes);
    var claimZones = getEligibleZones(claimAttributes_(row, claim));
    return {
      ok: true,
      zones: claimZones,
      rosterZones: rosterZones,
      claimZones: claimZones,
      reason: safeDecision_(claimAttributes_(row, claim)).reason
    };
  } catch (err) {
    return { ok: false, error: errText_(err), zones: [] };
  }
}

/* ===========================================================================
 * 3. Eligibility — an interpreter for the rule table in eligibility.json
 * ======================================================================== */

/**
 * Evaluates the eligibility rule table (SPEC §2.2) for one set of attributes.
 *
 * This is a rule-table interpreter. There is no knowledge of years, candidacy
 * or zone names anywhere in it — add a rule to config/eligibility.json, not a
 * branch here.
 *
 * Rules are tried top to bottom and THE FIRST MATCH WINS. A rule matches when
 * every key of its `when` object matches (AND); `when: {}` matches everyone.
 * Matcher forms, per SPEC §2.2:
 *   scalar     equality, trimmed, case-insensitive for strings, numeric when
 *              both sides look like numbers
 *   list       membership — any element matches
 *   {min,max}  inclusive numeric range, each bound optional
 *   {not: M}   negation of any of the above
 *
 * Validates: matcher shape, that attributes named in `when` exist, that
 * `allow_zones` is "*" or a list of zones defined in rooms.json, and that some
 * rule matched (i.e. the table really does end in a catch-all). Throws a
 * readable Error otherwise — a broken rule table must never quietly grant or
 * deny access.
 *
 * @param {Object} person Roster attributes (every CSV column, verbatim).
 * @return {Array<string>} Zone ids this person may sit in.
 */
function getEligibleZones(person) {
  return eligibilityDecision_(person).zones;
}

/** Full rule-table decision: which rule fired, why, and the resulting zones. */
function eligibilityDecision_(attrs) {
  var elig = cfg_('ELIGIBILITY_JSON');
  var rules = elig.rules;
  if (!isArray_(rules) || rules.length === 0) {
    throw new Error('eligibility.json: "rules" is missing or empty. There must be at ' +
      'least one rule, and the last one must be the catch-all {"when": {}}.');
  }

  var known = zoneIds_();
  for (var i = 0; i < rules.length; i++) {
    var rule = rules[i] || {};
    var where = 'eligibility.json: rules[' + i + ']' +
      (rule.id ? ' ("' + rule.id + '")' : '');
    if (predicateMatches_(attrs, rule.when || {}, where)) {
      return {
        ruleId: rule.id || ('rules[' + i + ']'),
        reason: rule.reason || '',
        zones: resolveAllowZones_(rule.allow_zones, known, where),
        error: null
      };
    }
  }
  throw new Error('eligibility.json: no rule matched. The last rule must be a ' +
    'catch-all ({"when": {}}) so that nobody can fall through with undefined ' +
    'eligibility (SPEC §2.2).');
}

/** eligibilityDecision_ that degrades to zero zones instead of throwing. */
function safeDecision_(attrs) {
  try {
    return eligibilityDecision_(attrs);
  } catch (err) {
    return { ruleId: null, reason: '', zones: [], error: errText_(err) };
  }
}

/** True when every key of `when` matches the corresponding attribute (AND). */
function predicateMatches_(attrs, when, where) {
  if (when === null || typeof when !== 'object' || isArray_(when)) {
    throw new Error(where + ': "when" must be an object. {} means "matches everyone".');
  }
  var keys = Object.keys(when);
  for (var i = 0; i < keys.length; i++) {
    var key = keys[i];
    var found = lookupAttribute_(attrs, key);
    if (!found.present) {
      throw new Error(where + ': "when" references attribute "' + key + '", which is ' +
        'not a column in roster.csv. Known columns: ' + Object.keys(attrs || {}).sort().join(', ') + '.');
    }
    if (!matcherMatches_(found.value, when[key], where + '.when.' + key)) {
      return false;
    }
  }
  return true;   // includes the {} catch-all
}

/** One attribute vs one matcher. Recursive: `not` and list elements reuse this. */
function matcherMatches_(value, matcher, where) {
  if (isArray_(matcher)) {                       // list membership
    for (var i = 0; i < matcher.length; i++) {
      if (matcherMatches_(value, matcher[i], where + '[' + i + ']')) return true;
    }
    return false;
  }
  if (matcher !== null && typeof matcher === 'object') {
    var keys = Object.keys(matcher);
    if (keys.indexOf('not') >= 0) {              // negation
      if (keys.length > 1) {
        throw new Error(where + ': {"not": ...} cannot be combined with other keys ' +
          '(found: ' + keys.sort().join(', ') + '). Nest them instead.');
      }
      return !matcherMatches_(value, matcher.not, where + '.not');
    }
    if (keys.indexOf('min') >= 0 || keys.indexOf('max') >= 0) {   // inclusive range
      for (var j = 0; j < keys.length; j++) {
        if (keys[j] !== 'min' && keys[j] !== 'max') {
          throw new Error(where + ': range matchers accept only "min" and "max"; ' +
            'found "' + keys[j] + '".');
        }
      }
      var n = toNumber_(value);
      if (n === null) return false;              // non-numeric attribute, no range match
      if (keys.indexOf('min') >= 0) {
        var min = toNumber_(matcher.min);
        if (min === null) throw new Error(where + '.min: not a number.');
        if (n < min) return false;
      }
      if (keys.indexOf('max') >= 0) {
        var max = toNumber_(matcher.max);
        if (max === null) throw new Error(where + '.max: not a number.');
        if (n > max) return false;
      }
      return true;
    }
    throw new Error(where + ': unsupported matcher ' + JSON.stringify(matcher) +
      '. Allowed forms are a scalar, a list, {"min":..,"max":..} or {"not": ..} ' +
      '(SPEC §2.2).');
  }
  return scalarEquals_(value, matcher);          // scalar equality
}

/** Numeric when both sides are numeric; otherwise trimmed, case-insensitive. */
function scalarEquals_(a, b) {
  var na = toNumber_(a);
  var nb = toNumber_(b);
  if (na !== null && nb !== null) return na === nb;
  return normStr_(a) === normStr_(b);
}

/** "*" -> every zone in rooms.json; otherwise a validated list of zone ids. */
function resolveAllowZones_(allowZones, known, where) {
  if (allowZones === '*') return known.slice();
  if (!isArray_(allowZones)) {
    throw new Error(where + ': "allow_zones" must be "*" or a list of zone ids. ' +
      'Defined zones are: ' + known.join(', ') + '.');
  }
  var out = [];
  for (var i = 0; i < allowZones.length; i++) {
    var z = String(allowZones[i]);
    if (known.indexOf(z) < 0) {
      throw new Error(where + ': allow_zones references zone "' + z + '", which is not ' +
        'defined in rooms.json:zones. Defined zones are: ' + known.join(', ') + '.');
    }
    if (out.indexOf(z) < 0) out.push(z);
  }
  return out;
}

/* ===========================================================================
 * 4. Submission
 * ======================================================================== */

/**
 * Validates and records one ranking. This is the only write path in the app.
 *
 * The browser has already checked all of this; none of that is trusted. Every
 * check below is re-run here against config/ and the roster, and every failure
 * is collected (not just the first) so the student can fix everything at once.
 *
 * Validates:
 *   - the config is loadable and the deadline (if set) has not passed
 *   - the cycle is in the RANKING phase. While PRELOCK_ENABLED is true the form
 *     is in the keeping-seats phase and this refuses outright: the roster has
 *     not been updated with the keepers yet, so a ranking taken now would be
 *     computed against a stale pool — desks that are about to leave it would
 *     still look available, and the person would have ranked desks nobody could
 *     be given. The client greys Choose and Confirm out; this is what makes it
 *     true.
 *   - the email is on the roster, and matches the signed-in user when Google
 *     identified them (unless ALLOW_PROXY_SUBMIT is set)
 *   - the person is not a desk-keeper — keepers are out of the pool (SPEC §3.4)
 *   - the person has not claimed a desk in the pre-lock step, which takes them
 *     out of the pool in exactly the same way
 *   - exactly K choices, each non-empty, all distinct
 *   - every choice is a real desk id from rooms.json, is not held by a keeper
 *     or by someone else's pre-lock claim, and is not marked "available": false
 *   - every chosen desk's zone is eligible under BOTH the roster attributes and
 *     the candidacy the student just confirmed (see the note below)
 *   - candidacy is non-empty
 *   - the Sheet header is the SPEC §3.1 header for this K
 *
 * On success appends exactly one row and returns its id. Rows are never
 * updated or deleted: re-submitting appends again and the solver keeps the
 * latest row per email (SPEC §3.2), so the history stays auditable.
 *
 * `payload.accommodation` — the optional private note — is NOT part of that
 * row. It goes to its own tab (section 6b) and cannot fail the submission:
 * it is never validated, never rejected, and if the note write fails the
 * ranking is still saved and `noteError` says so. The response row is exactly
 * the SPEC §3.1 row it has always been.
 *
 * Note on candidacy: SPEC §3.3 says the submission overrides the roster, and it
 * is recorded that way. For *eligibility* we take the intersection of
 * roster-derived and claim-derived zones, so nobody can unlock a zone by
 * retyping their candidacy, and so the form can never accept a pick the solver
 * would later rule ineligible under either reading.
 *
 * @param {Object} payload {email, name, candidacy, choices[], authMethod,
 *                          clientVersion, accommodation}.
 * @return {Object} {ok:true, submissionId, timestampIso, noteRecorded,
 *                   noteWithdrawn, noteTruncated, noteError} |
 *                  {ok:false, errors:[strings]}.
 */
function submitRanking(payload) {
  var errors = [];
  payload = (payload && typeof payload === 'object') ? payload : {};

  var k, deskIndex, roster;
  try {
    k = primaryCurve_().length;
    deskIndex = deskIndex_();
    roster = rosterRows_();
  } catch (err) {
    return fail_(['The desk configuration could not be loaded, so nothing was saved. ' +
      errText_(err)]);
  }

  // ---- deadline ---------------------------------------------------------
  var deadline = deadline_();
  if (deadline.passed) {
    return fail_(['The form closed at ' + deadline.iso + '. Nothing was saved. ' +
      'Email the coordinator if you missed it.']);
  }

  // ---- phase ------------------------------------------------------------
  // Pre-lock and ranking are two phases, not two available steps, and this is
  // where that is enforced rather than merely displayed. Refusing early, before
  // anything is read or written, is deliberate: there is no partial state to
  // clean up and no row to supersede.
  //
  // This is NOT the same thing as the claim check further down. That one is
  // about one person holding one desk and is enforced in BOTH phases. This one
  // is about the whole form being in the wrong half of the process.
  if (phase_() === PHASE_PRELOCK) {
    return fail_([rankingClosedMessage_()]);
  }

  // ---- identity ---------------------------------------------------------
  var email = normEmail_(payload.email);
  var person = null;
  if (!email) {
    errors.push('No email address was submitted. Reload the page and choose your name.');
  } else {
    person = findRosterRow_(roster, email);
    if (!person) {
      errors.push('"' + email + '" is not on the department roster, so it cannot enter the ' +
        'desk pool. Email the coordinator to be added.');
    } else if (person.keepsDesk) {
      errors.push(person.name + ' is down as keeping ' +
        deskDescription_(deskIndex, person.currentDesk) + ', so is not in the draw. ' +
        'If that is wrong, the roster needs fixing before you can submit.');
    }
  }

  // A Google identity, when we have one, pins the submission to that person.
  // Self-select is a convenience for people we cannot identify, not a way to
  // submit as someone else (SPEC §8).
  var sessionEmail = activeEmail_();
  var authMethod = AUTH_SELF_SELECT;
  if (sessionEmail && email && sessionEmail === email) {
    authMethod = AUTH_GOOGLE;
  } else if (sessionEmail && email && sessionEmail !== email && !proxySubmitAllowed_()) {
    errors.push('You are signed in as ' + sessionEmail + ' but tried to submit as ' + email +
      '. Sign in as yourself, or ask the coordinator to enter this one for you.');
  }

  // ---- pre-lock claim ---------------------------------------------------
  // Claiming a desk is a way out of the ranking, so someone holding a claim
  // cannot also submit one. Releasing the desk puts them back in the pool.
  //
  // NOT gated on PRELOCK_ENABLED. getBootstrap() reads claims unconditionally
  // too, so the two agree and this can never reject a ranking the form invited.
  // Switching the step off stops new claims; it does not release existing ones.
  // See the comment in getBootstrap().
  var keepers = null;
  if (person) {
    try {
      keepers = readKeepers_();
    } catch (errKeep) {
      keepers = null;                                  // no Keepers tab yet: nobody has claimed
    }
    var ownClaim = keepers ? activeClaimFor_(keepers, person.email) : null;
    if (ownClaim) {
      errors.push('You claimed ' + deskDescription_(deskIndex, ownClaim.deskId) +
        ' in the pre-lock step and are keeping it, so you are not in the ranking. ' +
        'Release that desk first if you would rather move.');
    }
  }

  // ---- candidacy the student just confirmed -----------------------------
  var candidacy = '';
  if (person) {
    candidacy = String(payload.candidacy === undefined || payload.candidacy === null
      ? '' : payload.candidacy).trim() || String(person.candidacy || '').trim();
    if (!candidacy) {
      errors.push('Candidacy is blank and the roster does not have one either. ' +
        'Tell the coordinator.');
    }
  }

  // ---- eligible zones ---------------------------------------------------
  var allowedZones = null;
  var eligibilityReason = '';
  if (person) {
    try {
      // The SUBMITTED candidacy governs, on its own.
      //
      // This used to intersect the roster's zones with the submitted ones, as a
      // hedge against somebody widening their own eligibility. That hedge broke
      // the moment candidates stopped being allowed everywhere: a student whose
      // roster row says "candidate" correcting themselves to "precandidate" got
      // {candidate_side, senior_office} ∩ {precandidate_side} = {} and was told
      // they had "no zone at all" — a dead end produced by using the field
      // exactly as intended.
      //
      // Intersecting is also the wrong policy here. The roster is stale by
      // design, the correction exists precisely to cross the cohort boundary,
      // and the department's position is that the student's own answer is the
      // one that counts. The conflict is still recorded for the coordinator's
      // report; it just no longer silently narrows anyone to nothing.
      var rosterZones = getEligibleZones(person.attributes);
      allowedZones = getEligibleZones(claimAttributes_(person, { candidacy: candidacy }));
      eligibilityReason = eligibilityDecision_(
        claimAttributes_(person, { candidacy: candidacy })
      ).reason;
      if (allowedZones.length === 0) {
        errors.push('The eligibility rules give "' + candidacy + '" nowhere to sit. ' +
          'That is a configuration bug rather than a decision about you — send ' +
          'this message to the coordinator.');
      }
    } catch (err2) {
      errors.push('Your eligibility could not be determined: ' + errText_(err2));
    }
  }

  // ---- the choices ------------------------------------------------------
  var canonical = [];
  var choices = payload.choices;
  if (!isArray_(choices)) {
    errors.push('No ranking was submitted.');
  } else {
    if (choices.length !== k) {
      errors.push('Exactly ' + k + ' choices are required, in order; ' + choices.length +
        ' ' + (choices.length === 1 ? 'was' : 'were') + ' submitted.');
    }
    var seenAt = {};
    var locked = lockedDeskMap_(roster);
    if (keepers) {
      var claimed = keepers.activeByDesk;
      Object.keys(claimed).forEach(function (deskId) {
        if (locked[deskId]) return;
        locked[deskId] = (claimed[deskId].name || claimed[deskId].email) +
          ' claimed this desk in the pre-lock step and is keeping it';
      });
    }
    for (var i = 0; i < choices.length; i++) {
      var rank = i + 1;
      var raw = (choices[i] === undefined || choices[i] === null) ? '' : String(choices[i]).trim();
      if (!raw) {
        errors.push('Choice ' + rank + ' is empty.');
        continue;
      }
      var desk = deskIndex[raw.toUpperCase()];
      if (!desk) {
        errors.push('Choice ' + rank + ' ("' + raw + '") is not a desk in this building. ' +
          'Reload the page — the floor plan may have changed.');
        continue;
      }
      if (seenAt[desk.id]) {
        errors.push(deskDescription_(deskIndex, desk.id) + ' is picked twice (choices ' +
          seenAt[desk.id] + ' and ' + rank + '). Each choice must be a different desk.');
      } else {
        seenAt[desk.id] = rank;
      }
      if (locked[desk.id]) {
        errors.push('Choice ' + rank + ', ' + deskDescription_(deskIndex, desk.id) +
          ', is not in the draw: ' + locked[desk.id] + '.');
      }
      if (desk.available === false) {
        errors.push('Choice ' + rank + ', ' + deskDescription_(deskIndex, desk.id) +
          ', has been taken out of the pool by the coordinator.');
      }
      if (allowedZones && allowedZones.indexOf(desk.zone) < 0) {
        errors.push('Choice ' + rank + ', ' + deskDescription_(deskIndex, desk.id) +
          ', is in ' + zoneLabel_(desk.zone) + ', which is not open to you' +
          (eligibilityReason ? ' — ' + eligibilityReason : '') +
          ' If your candidacy is out of date, ask the coordinator to fix the roster.');
      }
      canonical.push(desk.id);
    }
  }

  if (errors.length) return fail_(errors);

  // ---- the private note -------------------------------------------------
  // Read, never judged. A note cannot be wrong, cannot be too short and cannot
  // stop a ranking being saved, so nothing here appends to `errors`. Over-long
  // input is cut to the cap rather than refused (the browser stops at the cap
  // already; anything longer is not a person typing).
  var note = normaliseNote_(payload.accommodation);

  // ---- write ------------------------------------------------------------
  var lock = LockService.getScriptLock();
  try {
    lock.waitLock(LOCK_TIMEOUT_MS);
  } catch (errLock) {
    return fail_(['The response sheet was busy for ' + Math.round(LOCK_TIMEOUT_MS / 1000) +
      ' seconds and nothing was saved. Try again in a moment.']);
  }
  try {
    var sheet = getSheet_();
    ensureHeader_(sheet, k);

    var submissionId = Utilities.getUuid();
    var timestampIso = nowIso_();
    var row = HEADER_LEAD.map(function (col) {
      switch (col) {
        case 'submission_id': return submissionId;
        case 'timestamp': return timestampIso;
        case 'email': return email;
        case 'name': return String(payload.name || '').trim() || person.name;
        case 'candidacy': return candidacy;
        default: return '';
      }
    })
      .concat(canonical)
      .concat([
        String(payload.clientVersion || '').trim() || clientVersion_(),
        authMethod                                   // server-derived, never the client's word
      ]);

    sheet.appendRow(row);

    // Keep the timestamp a literal ISO-8601 string. Sheets will happily turn it
    // into a locale-formatted date on export otherwise, and SPEC §3.1 wants the
    // offset preserved.
    var tsCol = HEADER_LEAD.indexOf('timestamp') + 1;
    sheet.getRange(sheet.getLastRow(), tsCol).setNumberFormat('@').setValue(timestampIso);
    SpreadsheetApp.flush();

    // The ranking is now saved. The note is written second and inside its own
    // try, still under the same lock, so that a problem with the private tab
    // (missing permission, header edited by hand) reports itself as "your note
    // did not save" instead of throwing away a ranking that is already on disk.
    var noteWrite = { recorded: false, withdrawn: false, error: '' };
    try {
      noteWrite = recordAccommodation_(email, String(payload.name || '').trim() || person.name,
        note.text, String(payload.clientVersion || '').trim() || clientVersion_(), timestampIso);
    } catch (errNote) {
      noteWrite = { recorded: false, withdrawn: false, error: errText_(errNote) };
    }

    return {
      ok: true,
      submissionId: submissionId,
      timestampIso: timestampIso,
      noteRecorded: !!noteWrite.recorded,
      noteWithdrawn: !!noteWrite.withdrawn,
      noteTruncated: note.truncated,
      noteError: noteWrite.error || ''
    };
  } catch (errWrite) {
    return fail_(['Your ranking could not be saved: ' + errText_(errWrite) +
      ' Nothing was recorded — please try again, then tell the coordinator if it keeps failing.']);
  } finally {
    lock.releaseLock();
  }
}

/** Uniform failure envelope. */
function fail_(errors) {
  return { ok: false, errors: errors };
}

/* ===========================================================================
 * 5. The response Sheet
 * ======================================================================== */

/**
 * Finds (or creates) the response tab.
 *
 * The spreadsheet is RESPONSE_SPREADSHEET_ID if that script property is set,
 * otherwise the spreadsheet this script is bound to. The tab is
 * RESPONSE_SHEET_NAME, which is required — guessing a tab name is how you end
 * up with two half-filled sheets on deadline night.
 *
 * @return {Sheet}
 */
function getSheet_() {
  var name = String(prop_(PROP_SHEET_NAME) || '').trim();
  if (!name) {
    throw new Error('Script property "' + PROP_SHEET_NAME + '" is not set, so there is ' +
      'nowhere to write responses. Set it in Project Settings -> Script Properties to the ' +
      'name of the tab in the response spreadsheet (see frontend/DEPLOY.md).');
  }
  var ss = spreadsheet_();
  var sheet = ss.getSheetByName(name);
  if (!sheet) sheet = ss.insertSheet(name);
  return sheet;
}

/** The spreadsheet everything is written to. Shared by responses and keepers. */
function spreadsheet_() {
  var id = String(prop_(PROP_SPREADSHEET_ID) || '').trim();
  if (id) {
    try {
      return SpreadsheetApp.openById(id);
    } catch (err) {
      throw new Error('Script property "' + PROP_SPREADSHEET_ID + '" is "' + id + '", but ' +
        'that spreadsheet could not be opened. Check the id and that the deploying account ' +
        'can edit it. (' + errText_(err) + ')');
    }
  }
  var ss = SpreadsheetApp.getActiveSpreadsheet();
  if (!ss) {
    throw new Error('This script is not bound to a spreadsheet and script property "' +
      PROP_SPREADSHEET_ID + '" is not set, so there is nowhere to write anything.');
  }
  return ss;
}

/** The SPEC §3.1 header for a given K. choice_N columns are generated, never typed. */
function responseHeader_(k) {
  var choices = [];
  for (var i = 1; i <= k; i++) choices.push('choice_' + i);
  return HEADER_LEAD.concat(choices).concat(HEADER_TAIL);
}

/**
 * Writes the header on first use, and on every later use checks that the sheet
 * still matches the header this K implies. A sheet built for a different K (or
 * with reordered columns) would silently produce a response file the solver
 * rejects, so we refuse to append instead. Extra columns after ours are left
 * alone — coordinators do add scratch notes.
 */
function ensureHeader_(sheet, k) {
  var want = responseHeader_(k);
  var lastCol = sheet.getLastColumn();
  var lastRow = sheet.getLastRow();
  var have = (lastRow >= 1 && lastCol >= 1)
    ? sheet.getRange(1, 1, 1, lastCol).getValues()[0].map(function (v) { return String(v).trim(); })
    : [];

  var populated = have.filter(function (v) { return v !== ''; });
  if (populated.length === 0) {
    sheet.getRange(1, 1, 1, want.length).setValues([want]).setFontWeight('bold');
    sheet.setFrozenRows(1);
    var tsCol = HEADER_LEAD.indexOf('timestamp') + 1;
    sheet.getRange(1, tsCol, sheet.getMaxRows(), 1).setNumberFormat('@');
    return want;
  }

  for (var i = 0; i < want.length; i++) {
    if (have[i] !== want[i]) {
      throw new Error('The response sheet header does not match the current config. ' +
        'Column ' + (i + 1) + ' is "' + (have[i] === undefined ? '' : have[i]) + '" but K=' + k +
        ' requires "' + want[i] + '". Either scoring.json changed after collection started ' +
        '(do not do that mid-round) or the sheet was edited. Expected header: ' +
        want.join(', ') + '.');
    }
  }
  return have;
}

/**
 * Reads every submission in the sheet and resolves the latest one per email,
 * exactly as SPEC §3.2 does: newest timestamp wins, ties broken by later row.
 * The number of choice_N columns is discovered from the header, never assumed.
 *
 * @return {Object} {header, k, all:[...], latest:{email: submission}}.
 */
function readResponses_() {
  var sheet = getSheet_();
  var lastRow = sheet.getLastRow();
  var lastCol = sheet.getLastColumn();
  if (lastRow < 2 || lastCol < 1) {
    return { header: [], k: 0, all: [], latest: {} };
  }

  var values = sheet.getRange(1, 1, lastRow, lastCol).getValues();
  var header = values[0].map(function (v) { return String(v).trim(); });

  var col = {};
  var choiceCols = [];                                   // [{rank, index}]
  for (var c = 0; c < header.length; c++) {
    var m = /^choice_(\d+)$/.exec(header[c]);
    if (m) choiceCols.push({ rank: parseInt(m[1], 10), index: c });
    else if (header[c]) col[header[c]] = c;
  }
  choiceCols.sort(function (a, b) { return a.rank - b.rank; });

  var all = [];
  for (var r = 1; r < values.length; r++) {
    var rowVals = values[r];
    var email = normEmail_(cell_(rowVals, col.email));
    if (!email) continue;                                // blank / spacer row
    var choices = choiceCols.map(function (cc) { return String(rowVals[cc.index] || '').trim(); });
    all.push({
      submissionId: cell_(rowVals, col.submission_id),
      timestampIso: isoCell_(rowVals[col.timestamp]),
      email: email,
      name: cell_(rowVals, col.name),
      // `year` is no longer written. A sheet left over from an older cycle may
      // still have the column; read it if it is there, ignore it otherwise.
      year: col.year === undefined ? '' : rowVals[col.year],
      candidacy: cell_(rowVals, col.candidacy),
      choices: choices,
      clientVersion: cell_(rowVals, col.client_version),
      authMethod: cell_(rowVals, col.auth_method),
      fileRow: r - 1
    });
  }

  var latest = {};
  for (var i = 0; i < all.length; i++) {
    var s = all[i];
    var prev = latest[s.email];
    if (!prev || !laterThan_(prev, s)) latest[s.email] = s;
  }
  return { header: header, k: choiceCols.length, all: all, latest: latest };
}

/** True when `a` supersedes `b` (newer timestamp, ties broken by later row). */
function laterThan_(a, b) {
  var ta = Date.parse(a.timestampIso);
  var tb = Date.parse(b.timestampIso);
  if (!isNaN(ta) && !isNaN(tb) && ta !== tb) return ta > tb;
  return a.fileRow > b.fileRow;
}

/** desk id -> how many people currently have it as their first choice. */
function firstChoiceCounts_(responses) {
  var counts = {};
  var emails = Object.keys(responses.latest);
  for (var i = 0; i < emails.length; i++) {
    var top = responses.latest[emails[i]].choices[0];
    if (!top) continue;
    counts[top] = (counts[top] || 0) + 1;
  }
  return counts;
}

/* ===========================================================================
 * 6. The pre-lock step — claiming the desk you already sit at
 *
 * A student who is happy where they are can take themselves AND their desk out
 * of the draw rather than ranking anything. The claim log is a second
 * append-only tab with the same semantics as the response sheet: one row per
 * action, releasing writes a new row with keeping=false, and the latest row per
 * email wins. tools/merge_keepers.py folds the result into config/roster.csv,
 * which is where keeps_desk / current_desk actually live (SPEC §2.3, §3.4).
 *
 * Nothing here decides who *may* keep a desk beyond "it exists and nobody else
 * has it". In particular a claim is deliberately NOT checked against the
 * eligibility zones: the rule table says where somebody may be *assigned*, and
 * staying put is not an assignment. The coordinator sees every claim in the tab.
 * ======================================================================== */

/* The two phases. They are mutually exclusive by construction: there is one
 * script property and it has two values. */
var PHASE_PRELOCK = 'prelock';                 // keeping seats; ranking is shut
var PHASE_RANKING = 'ranking';                 // ranking; no new claims

/**
 * Which phase the cycle is in, as one word.
 *
 * getBootstrap() sends this so the client switches on a phase instead of
 * inferring one from prelock.enabled — the client used to read "an extra step
 * is available" out of that flag, and it now means "which half of the process
 * are we in". Never throws.
 */
function phase_() {
  return prelockSettings_().enabled ? PHASE_PRELOCK : PHASE_RANKING;
}

/**
 * Why ranking is shut and when it opens, quoted verbatim to a student who got
 * a ranking past the greyed-out UI anyway. PRELOCK_DEADLINE_ISO is named when
 * it is set, because "later" is not an answer somebody can plan around.
 */
function rankingClosedMessage_() {
  var prelock = prelockSettings_();
  var when = (prelock.deadlineIso && !prelock.deadlinePassed)
    ? ' That stage closes at ' + prelock.deadlineIso + ' and ranking opens after it.'
    : ' Ranking opens once that stage closes.';
  return 'Ranking has not opened yet: the form is still in the stage where people ' +
    'keep the desk they already sit at.' + when + ' Nothing was saved. Reload the ' +
    'page when the coordinator says ranking is open, and rank then.';
}

/** {enabled, deadlineIso, deadlinePassed} for the pre-lock step. Never throws. */
function prelockSettings_() {
  var enabled = String(prop_(PROP_PRELOCK_ENABLED) || '').trim().toLowerCase() === 'true';
  var iso = String(prop_(PROP_PRELOCK_DEADLINE_ISO) || '').trim();
  if (!iso) return { enabled: enabled, deadlineIso: null, deadlinePassed: false };
  var when = Date.parse(iso);
  if (isNaN(when)) {
    console.warn('Script property ' + PROP_PRELOCK_DEADLINE_ISO + ' is not a parseable ' +
      'ISO-8601 instant ("' + iso + '"); ignoring it.');
    return { enabled: enabled, deadlineIso: null, deadlinePassed: false };
  }
  return { enabled: enabled, deadlineIso: iso, deadlinePassed: Date.now() > when };
}

/** Tab the claims live in. */
function keepersSheetName_() {
  return String(prop_(PROP_KEEPERS_SHEET_NAME) || '').trim() || DEFAULT_KEEPERS_SHEET;
}

/**
 * The Keepers tab. Returns null when it does not exist and `create` is falsy,
 * which is the normal state before the first claim — reading must not create a
 * tab as a side effect of somebody merely opening the form.
 */
function keepersSheet_(create) {
  var ss = spreadsheet_();
  var name = keepersSheetName_();
  var sheet = ss.getSheetByName(name);
  if (!sheet && create) sheet = ss.insertSheet(name);
  return sheet || null;
}

/** Writes the header on first use; refuses to append to a mismatched tab. */
function ensureKeepersHeader_(sheet) {
  var lastCol = sheet.getLastColumn();
  var lastRow = sheet.getLastRow();
  var have = (lastRow >= 1 && lastCol >= 1)
    ? sheet.getRange(1, 1, 1, lastCol).getValues()[0].map(function (v) { return String(v).trim(); })
    : [];

  if (have.filter(function (v) { return v !== ''; }).length === 0) {
    sheet.getRange(1, 1, 1, KEEPERS_HEADER.length).setValues([KEEPERS_HEADER]).setFontWeight('bold');
    sheet.setFrozenRows(1);
    var tsCol = KEEPERS_HEADER.indexOf('timestamp') + 1;
    sheet.getRange(1, tsCol, sheet.getMaxRows(), 1).setNumberFormat('@');
    return KEEPERS_HEADER;
  }

  for (var i = 0; i < KEEPERS_HEADER.length; i++) {
    if (have[i] !== KEEPERS_HEADER[i]) {
      throw new Error('The "' + keepersSheetName_() + '" tab does not have the expected ' +
        'header. Column ' + (i + 1) + ' is "' + (have[i] === undefined ? '' : have[i]) +
        '" but should be "' + KEEPERS_HEADER[i] + '". Expected header: ' +
        KEEPERS_HEADER.join(', ') + '. Rename or clear that tab rather than editing it.');
    }
  }
  return have;
}

/**
 * Every claim row, plus the latest row per email and the desks those latest
 * rows are keeping. Identical resolution to readResponses_ (SPEC §3.2).
 *
 * @return {Object} {all:[...], latest:{email: row}, activeByDesk:{deskId: row}}.
 */
function readKeepers_() {
  var empty = { all: [], latest: {}, activeByDesk: {} };
  var sheet = keepersSheet_(false);
  if (!sheet) return empty;

  var lastRow = sheet.getLastRow();
  var lastCol = sheet.getLastColumn();
  if (lastRow < 2 || lastCol < 1) return empty;

  var values = sheet.getRange(1, 1, lastRow, lastCol).getValues();
  var header = values[0].map(function (v) { return String(v).trim(); });
  var col = {};
  for (var c = 0; c < header.length; c++) if (header[c]) col[header[c]] = c;

  var all = [];
  for (var r = 1; r < values.length; r++) {
    var rowVals = values[r];
    var email = normEmail_(cell_(rowVals, col.email));
    if (!email) continue;                                // blank / spacer row
    all.push({
      claimId: cell_(rowVals, col.claim_id),
      timestampIso: isoCell_(rowVals[col.timestamp]),
      email: email,
      name: cell_(rowVals, col.name),
      deskId: cell_(rowVals, col.desk_id),
      keeping: truthy_(col.keeping === undefined ? '' : rowVals[col.keeping]),
      clientVersion: cell_(rowVals, col.client_version),
      fileRow: r - 1
    });
  }

  var latest = {};
  for (var i = 0; i < all.length; i++) {
    var row = all[i];
    var prev = latest[row.email];
    if (!prev || !laterThan_(prev, row)) latest[row.email] = row;
  }

  var activeByDesk = {};
  Object.keys(latest).forEach(function (email) {
    var row = latest[email];
    if (row.keeping && row.deskId) activeByDesk[row.deskId] = row;
  });

  return { all: all, latest: latest, activeByDesk: activeByDesk };
}

/** The desk this email is currently keeping, or null. */
function activeClaimFor_(keepers, email) {
  var row = keepers.latest[normEmail_(email)];
  return (row && row.keeping && row.deskId) ? row : null;
}

/**
 * Live claims, as the client needs them: [{deskId, email, name, timestampIso}].
 * Sorted by desk id so the payload is stable between calls.
 */
function activeClaims_(roster) {
  var keepers = readKeepers_();
  var byDesk = keepers.activeByDesk;
  return Object.keys(byDesk).sort().map(function (deskId) {
    var row = byDesk[deskId];
    var person = roster ? findRosterRow_(roster, row.email) : null;
    return {
      deskId: deskId,
      email: row.email,
      name: (person && person.name) || row.name || row.email,
      timestampIso: row.timestampIso
    };
  });
}

/**
 * Records one pre-lock claim, or one release. The only other write path in the
 * app, and it is append-only for the same reason submitRanking() is.
 *
 * Re-validates everything the browser checked:
 *   - the step is switched on, and neither deadline has passed
 *   - the email is on the roster, and matches the signed-in user when Google
 *     identified them (unless ALLOW_PROXY_SUBMIT is set)
 *   - the desk exists in rooms.json and is in the pool
 *   - nobody else is already keeping it — held under a script lock, so two
 *     people tapping the same desk at the same moment cannot both win
 *   - a release names a desk this person is actually keeping
 *
 * @param {Object} payload {email, name, deskId, keeping, clientVersion}.
 * @return {Object} {ok:true, claimId, timestampIso, deskId, keeping} |
 *                  {ok:false, errors:[strings]}.
 */
function claimDesk(payload) {
  payload = (payload && typeof payload === 'object') ? payload : {};
  var keeping = payload.keeping !== false && truthy_(
    payload.keeping === undefined ? true : payload.keeping);
  var errors = [];

  // The mirror image of the phase check in submitRanking(): claims are only
  // taken in phase 1, rankings only in phase 2, and each path refuses in the
  // other phase. Note this stops NEW claims only — claims already made are
  // still honoured in phase 2, which is the whole point of merging them into
  // the roster before it starts.
  var prelock = prelockSettings_();
  if (!prelock.enabled) {
    return fail_(['The stage for keeping your current desk is not open, so nothing ' +
      'was saved. Rank your desks as normal — that is the step that is live now.']);
  }

  var deskIndex, roster;
  try {
    deskIndex = deskIndex_();
    roster = rosterRows_();
  } catch (err) {
    return fail_(['The desk configuration could not be loaded, so nothing was saved. ' +
      errText_(err)]);
  }

  var deadline = deadline_();
  if (deadline.passed) {
    return fail_(['The form closed at ' + deadline.iso + '. Nothing was saved.']);
  }
  if (prelock.deadlinePassed) {
    return fail_(['The deadline for keeping your current desk passed at ' +
      prelock.deadlineIso + '. Nothing was saved — email the coordinator.']);
  }

  // ---- identity ---------------------------------------------------------
  var email = normEmail_(payload.email);
  var person = null;
  if (!email) {
    errors.push('No email address was submitted. Reload the page and choose your name.');
  } else {
    person = findRosterRow_(roster, email);
    if (!person) {
      errors.push('"' + email + '" is not on the department roster, so it cannot claim a ' +
        'desk. Email the coordinator to be added.');
    }
  }
  var sessionEmail = activeEmail_();
  if (sessionEmail && email && sessionEmail !== email && !proxySubmitAllowed_()) {
    errors.push('You are signed in as ' + sessionEmail + ' but tried to claim a desk as ' +
      email + '. Sign in as yourself, or ask the coordinator to enter this one for you.');
  }

  // ---- the desk ---------------------------------------------------------
  var raw = String(payload.deskId === undefined || payload.deskId === null
    ? '' : payload.deskId).trim();
  var desk = raw ? deskIndex[raw.toUpperCase()] : null;
  if (!raw) {
    errors.push('No desk was named, so there is nothing to ' + (keeping ? 'claim' : 'release') + '.');
  } else if (!desk) {
    errors.push('"' + raw + '" is not a desk in this building. Reload the page — the floor ' +
      'plan may have changed.');
  } else if (keeping && desk.available === false) {
    errors.push(deskDescription_(deskIndex, desk.id) + ' has been taken out of the pool by ' +
      'the coordinator, so it cannot be claimed. Email them.');
  }

  if (keeping && desk && person) {
    var locked = lockedDeskMap_(roster);
    if (locked[desk.id] && !(person.keepsDesk && person.currentDesk === desk.id)) {
      errors.push(deskDescription_(deskIndex, desk.id) + ' is already down on the roster as ' +
        'kept: ' + locked[desk.id] + '.');
    }
  }

  if (errors.length) return fail_(errors);

  // ---- write ------------------------------------------------------------
  // The "is it taken" read has to happen inside the lock, or two people can
  // both read "free" and both write a claim for the same desk.
  var lock = LockService.getScriptLock();
  try {
    lock.waitLock(LOCK_TIMEOUT_MS);
  } catch (errLock) {
    return fail_(['The claim sheet was busy for ' + Math.round(LOCK_TIMEOUT_MS / 1000) +
      ' seconds and nothing was saved. Try again in a moment.']);
  }
  try {
    var keepers = readKeepers_();
    var held = keepers.activeByDesk[desk.id];
    if (keeping && held && held.email !== email) {
      return fail_([(held.name || held.email) + ' claimed ' +
        deskDescription_(deskIndex, desk.id) + ' first, so it is no longer available. ' +
        'Pick a different desk, or go on to rank desks instead.']);
    }
    if (!keeping) {
      var own = activeClaimFor_(keepers, email);
      if (!own) {
        return fail_(['You are not currently keeping a desk, so there is nothing to release. ' +
          'Reload the page to see where things stand.']);
      }
      if (own.deskId !== desk.id) {
        return fail_(['You are keeping ' + deskDescription_(deskIndex, own.deskId) +
          ', not ' + deskDescription_(deskIndex, desk.id) + '. Reload the page.']);
      }
    }

    var sheet = keepersSheet_(true);
    ensureKeepersHeader_(sheet);

    var claimId = Utilities.getUuid();
    var timestampIso = nowIso_();
    var row = KEEPERS_HEADER.map(function (colName) {
      switch (colName) {
        case 'claim_id': return claimId;
        case 'timestamp': return timestampIso;
        case 'email': return email;
        case 'name': return String(payload.name || '').trim() || person.name;
        case 'desk_id': return desk.id;
        case 'keeping': return keeping ? 'yes' : 'no';
        case 'client_version': return String(payload.clientVersion || '').trim() || clientVersion_();
        default: return '';
      }
    });

    sheet.appendRow(row);
    var tsCol = KEEPERS_HEADER.indexOf('timestamp') + 1;
    sheet.getRange(sheet.getLastRow(), tsCol).setNumberFormat('@').setValue(timestampIso);
    SpreadsheetApp.flush();

    return {
      ok: true,
      claimId: claimId,
      timestampIso: timestampIso,
      deskId: desk.id,
      keeping: keeping
    };
  } catch (errWrite) {
    return fail_(['Your ' + (keeping ? 'claim' : 'release') + ' could not be saved: ' +
      errText_(errWrite) + ' Nothing was recorded — please try again, then tell the ' +
      'coordinator if it keeps failing.']);
  } finally {
    lock.releaseLock();
  }
}

/* ===========================================================================
 * 6b. Private notes to the coordinator — CONFIDENTIAL
 *
 * The last page of the form has an optional box for the one thing a ranked
 * list cannot say: *where* a person needs to sit, and why. Accessibility, a
 * health need, needing distance from a particular person in order to work.
 *
 * Three rules, all of them load-bearing.
 *
 *   1. It is not an input to the solve. SPEC I2 says the assignment is a pure
 *      function of (responses, config, seed) with no override path, and that is
 *      the whole integrity argument. A note is advice to a human being. If the
 *      coordinator decides to act on one they change an INPUT — mark a desk
 *      unavailable in rooms.json, say — which is visible in git. Do not add a
 *      weight, a nudge or a constraint here, and do not teach the solver to
 *      read this tab.
 *
 *   2. It never reaches anything published. These notes name other people
 *      ("I need to be away from X") and disclose health and caring situations,
 *      so pseudonymising the author does not make them safe. They are written
 *      to their own tab and to nothing else: not the response row, therefore
 *      not responses.csv, not responses_anonymized.csv, not results.json and
 *      not the public PDF. Getting one into a published artefact is a
 *      correctness bug, not a tidiness issue.
 *
 *   3. It cannot cost anybody their submission. Nothing in this section
 *      validates, and nothing in it can make submitRanking() fail.
 *
 * The log is append-only with the same semantics as the response sheet and the
 * Keepers tab (SPEC §3.2): one row per submission that carried a note, latest
 * row per email wins. Clearing the box on a later submission appends a row with
 * an EMPTY note, which is how a note is withdrawn — exactly as releasing a desk
 * appends keeping=no rather than deleting the claim. A submission with no note
 * from somebody who never wrote one appends nothing at all, so the tab stays
 * short enough to read.
 *
 * The row's timestamp is the submission's timestamp, so a note lines up with
 * the response row it arrived with without either file naming the other.
 * ======================================================================== */

/** Tab the private notes live in. */
function accommodationsSheetName_() {
  return String(prop_(PROP_ACCOMMODATIONS_SHEET_NAME) || '').trim() ||
    DEFAULT_ACCOMMODATIONS_SHEET;
}

/**
 * The Accommodations tab. Returns null when it does not exist and `create` is
 * falsy — the normal state until somebody writes the first note. Reading must
 * never create it: an empty confidential tab appearing in the spreadsheet the
 * day the form opens invites the question "what is in there".
 */
function accommodationsSheet_(create) {
  var ss = spreadsheet_();
  var name = accommodationsSheetName_();
  var sheet = ss.getSheetByName(name);
  if (!sheet && create) sheet = ss.insertSheet(name);
  return sheet || null;
}

/** Writes the header on first use; refuses to append to a mismatched tab. */
function ensureAccommodationsHeader_(sheet) {
  var lastCol = sheet.getLastColumn();
  var lastRow = sheet.getLastRow();
  var have = (lastRow >= 1 && lastCol >= 1)
    ? sheet.getRange(1, 1, 1, lastCol).getValues()[0].map(function (v) { return String(v).trim(); })
    : [];

  if (have.filter(function (v) { return v !== ''; }).length === 0) {
    sheet.getRange(1, 1, 1, ACCOMMODATIONS_HEADER.length)
      .setValues([ACCOMMODATIONS_HEADER]).setFontWeight('bold');
    sheet.setFrozenRows(1);
    // Plain text, whole column, for both of these: the timestamp so the offset
    // survives export (SPEC §3.1), and the note so that a line beginning "=" or
    // "+" is a sentence rather than a formula Sheets tries to evaluate.
    var tsColNew = ACCOMMODATIONS_HEADER.indexOf('timestamp') + 1;
    var noteColNew = ACCOMMODATIONS_HEADER.indexOf('note') + 1;
    sheet.getRange(1, tsColNew, sheet.getMaxRows(), 1).setNumberFormat('@');
    sheet.getRange(1, noteColNew, sheet.getMaxRows(), 1).setNumberFormat('@').setWrap(true);
    return ACCOMMODATIONS_HEADER;
  }

  for (var i = 0; i < ACCOMMODATIONS_HEADER.length; i++) {
    if (have[i] !== ACCOMMODATIONS_HEADER[i]) {
      throw new Error('The "' + accommodationsSheetName_() + '" tab does not have the ' +
        'expected header. Column ' + (i + 1) + ' is "' + (have[i] === undefined ? '' : have[i]) +
        '" but should be "' + ACCOMMODATIONS_HEADER[i] + '". Expected header: ' +
        ACCOMMODATIONS_HEADER.join(', ') + '. Rename or clear that tab rather than editing it.');
    }
  }
  return have;
}

/**
 * Trims and caps one note. Never throws, never rejects.
 *
 * @param {*} value Whatever the client sent.
 * @return {Object} {text, truncated}.
 */
function normaliseNote_(value) {
  if (value === undefined || value === null) return { text: '', truncated: false };
  var text = String(value).replace(/\r\n?/g, '\n').replace(/^\s+|\s+$/g, '');
  if (text.length <= ACCOMMODATION_MAX_CHARS) return { text: text, truncated: false };
  return {
    text: text.slice(0, ACCOMMODATION_MAX_CHARS).replace(/\s+$/, ''),
    truncated: true
  };
}

/**
 * Every note row, plus the latest per email. Same resolution as
 * readResponses_ / readKeepers_ (SPEC §3.2).
 *
 * @return {Object} {all:[...], latest:{email: row}}.
 */
function readAccommodations_() {
  var empty = { all: [], latest: {} };
  var sheet = accommodationsSheet_(false);
  if (!sheet) return empty;

  var lastRow = sheet.getLastRow();
  var lastCol = sheet.getLastColumn();
  if (lastRow < 2 || lastCol < 1) return empty;

  var values = sheet.getRange(1, 1, lastRow, lastCol).getValues();
  var header = values[0].map(function (v) { return String(v).trim(); });
  var col = {};
  for (var c = 0; c < header.length; c++) if (header[c]) col[header[c]] = c;

  var all = [];
  for (var r = 1; r < values.length; r++) {
    var rowVals = values[r];
    var email = normEmail_(cell_(rowVals, col.email));
    if (!email) continue;                                // blank / spacer row
    all.push({
      noteId: cell_(rowVals, col.note_id),
      timestampIso: isoCell_(rowVals[col.timestamp]),
      email: email,
      name: cell_(rowVals, col.name),
      // Not trimmed to nothing and not cell_()'d: a note keeps its own line
      // breaks. Only the outer whitespace goes.
      note: col.note === undefined ? ''
        : String(rowVals[col.note] === undefined || rowVals[col.note] === null
          ? '' : rowVals[col.note]).replace(/^\s+|\s+$/g, ''),
      clientVersion: cell_(rowVals, col.client_version),
      fileRow: r - 1
    });
  }

  var latest = {};
  for (var i = 0; i < all.length; i++) {
    var row = all[i];
    var prev = latest[row.email];
    if (!prev || !laterThan_(prev, row)) latest[row.email] = row;
  }
  return { all: all, latest: latest };
}

/**
 * The note this person's most recent submission carried, or null when they
 * have never written one. A row whose note is empty is a withdrawal and is
 * returned as such (note: '') — that is still the latest thing they said.
 */
function latestAccommodationFor_(email) {
  var row = readAccommodations_().latest[normEmail_(email)];
  return row || null;
}

/**
 * Appends one note row. Called from inside submitRanking()'s lock, after the
 * response row is safely written.
 *
 * An empty note from somebody with no note on file writes nothing: most people
 * leave the box alone and the tab should not fill up with blanks. An empty note
 * from somebody who DOES have one on file writes a blank row, which withdraws
 * it — otherwise clearing the box would silently leave the old note standing as
 * the latest word.
 *
 * @return {Object} {recorded, withdrawn, error, noteId?}.
 */
function recordAccommodation_(email, name, text, clientVersion, timestampIso) {
  var withdrawing = false;
  if (!text) {
    var prior = latestAccommodationFor_(email);
    if (!prior || !prior.note) return { recorded: false, withdrawn: false, error: '' };
    withdrawing = true;
  }

  var sheet = accommodationsSheet_(true);
  ensureAccommodationsHeader_(sheet);

  var noteId = Utilities.getUuid();
  var row = ACCOMMODATIONS_HEADER.map(function (colName) {
    switch (colName) {
      case 'note_id': return noteId;
      case 'timestamp': return timestampIso;
      case 'email': return email;
      case 'name': return name;
      case 'note': return text;
      case 'client_version': return clientVersion;
      default: return '';
    }
  });

  sheet.appendRow(row);

  // Re-set both cells as plain text. appendRow() will read "=" or "+" at the
  // start of a note as a formula, and will re-format the timestamp as a date.
  var written = sheet.getLastRow();
  var tsCol = ACCOMMODATIONS_HEADER.indexOf('timestamp') + 1;
  var noteCol = ACCOMMODATIONS_HEADER.indexOf('note') + 1;
  sheet.getRange(written, tsCol).setNumberFormat('@').setValue(timestampIso);
  sheet.getRange(written, noteCol).setNumberFormat('@').setValue(text);
  SpreadsheetApp.flush();

  return {
    recorded: !withdrawing,
    withdrawn: withdrawing,
    error: '',
    noteId: noteId
  };
}

/* ===========================================================================
 * 7. Config access helpers (everything here reads ConfigData.gs)
 * ======================================================================== */

/** Fetches a generated global, with a message that says how to create it. */
function cfg_(name) {
  var g = (typeof globalThis !== 'undefined') ? globalThis : this;
  if (typeof g[name] === 'undefined' || g[name] === null) {
    throw new Error('ConfigData.gs does not define ' + name + '. Regenerate it with ' +
      '`python3 tools/sync_config.py` and push it with clasp — it is a generated file.');
  }
  return g[name];
}

/** cfg_ with a default, for values the app can live without. */
function safeCfg_(name, fallback) {
  try {
    return cfg_(name);
  } catch (err) {
    return fallback;
  }
}

/** The primary scoring curve. Its length is K — K is never written down. */
function primaryCurve_() {
  var scoring = cfg_('SCORING_JSON');
  var name = scoring.primary_curve;
  var curves = scoring.curves || {};
  if (!name || !isArray_(curves[name])) {
    throw new Error('scoring.json: primary_curve is "' + name + '" but curves["' + name +
      '"] is not a list. K is the length of that list, so nothing can run without it.');
  }
  if (curves[name].length === 0) {
    throw new Error('scoring.json: curves["' + name + '"] is empty, so K would be 0.');
  }
  return curves[name].slice();
}

/** Every desk in every room, each tagged with its room. */
function allDesks_() {
  var rooms = cfg_('ROOMS_JSON').rooms || [];
  var out = [];
  for (var r = 0; r < rooms.length; r++) {
    var desks = rooms[r].desks || [];
    for (var d = 0; d < desks.length; d++) {
      var desk = desks[d];
      out.push({
        id: String(desk.id),
        label: String(desk.label === undefined ? desk.id : desk.label),
        zone: String(desk.zone),
        roomId: String(rooms[r].id),
        roomLabel: String(rooms[r].label || rooms[r].id),
        available: desk.available === false ? false : true,
        notes: desk.notes || ''
      });
    }
  }
  return out;
}

/** UPPERCASED desk id -> desk, so a stray "d07" from the client still resolves. */
function deskIndex_() {
  var idx = {};
  var desks = allDesks_();
  for (var i = 0; i < desks.length; i++) idx[desks[i].id.toUpperCase()] = desks[i];
  return idx;
}

/** Zone ids defined in rooms.json, in file order. */
function zoneIds_() {
  return Object.keys(cfg_('ROOMS_JSON').zones || {});
}

/** Human label for a zone, for error messages. */
function zoneLabel_(zoneId) {
  var zones = safeCfg_('ROOMS_JSON', {}).zones || {};
  var z = zones[zoneId];
  return (z && z.label) ? ('the ' + z.label) : ('zone "' + zoneId + '"');
}

/** "desk 7" / "desk D07" for error messages. */
function deskDescription_(deskIndex, deskId) {
  var desk = deskIndex[String(deskId || '').toUpperCase()];
  return desk ? ('desk ' + desk.label + ' (' + desk.id + ')') : ('desk "' + deskId + '"');
}

/**
 * The roster, normalised. `attributes` keeps every CSV column verbatim so that
 * eligibility rules can reference columns this code has never heard of.
 */
function rosterRows_() {
  var raw = cfg_('ROSTER');
  if (!isArray_(raw)) {
    throw new Error('ConfigData.gs: ROSTER is not a list. Regenerate it with tools/sync_config.py.');
  }
  var out = [];
  for (var i = 0; i < raw.length; i++) {
    var row = raw[i] || {};
    var attributes = {};
    Object.keys(row).forEach(function (key) { attributes[key] = row[key]; });   // eslint-disable-line no-loop-func
    var yearRaw = pick_(row, 'year');
    out.push({
      email: normEmail_(pick_(row, 'email')),
      name: String(pick_(row, 'name') || '').trim(),
      year: toNumber_(yearRaw) === null ? yearRaw : toNumber_(yearRaw),
      candidacy: String(pick_(row, 'candidacy') || '').trim(),
      keepsDesk: truthy_(pick_(row, 'keeps_desk')),
      currentDesk: String(pick_(row, 'current_desk') || '').trim(),
      attributes: attributes
    });
  }
  return out;
}

/** Roster lookup by normalised email. */
function findRosterRow_(roster, email) {
  if (!email) return null;
  for (var i = 0; i < roster.length; i++) {
    if (roster[i].email === email) return roster[i];
  }
  return null;
}

/**
 * Roster attributes with the candidacy the student just confirmed layered on
 * top (SPEC §3.3: the submission wins). Column names are matched
 * case-insensitively so an oddly-cased header still gets overridden.
 *
 * CONFIRMED_FIELDS is the list of roster columns the form lets a student
 * correct. It is one entry long on purpose: candidacy is the only attribute the
 * form collects, so it is the only one that can override the roster. Everything
 * else — including `year`, which eligibility rules may still reference — is
 * taken from the roster untouched.
 */
var CONFIRMED_FIELDS = ['candidacy'];

function claimAttributes_(rosterRow, claim) {
  var attrs = {};
  Object.keys(rosterRow.attributes).forEach(function (key) { attrs[key] = rosterRow.attributes[key]; });
  CONFIRMED_FIELDS.forEach(function (field) {
    var value = claim[field];
    if (value === undefined || value === null || String(value).trim() === '') return;
    attrs[attributeKey_(attrs, field)] = String(value).trim();
  });
  return attrs;
}

/** Desks held by keepers: [{deskId, reason}]. Those desks are out of the pool. */
function lockedDesks_(roster) {
  var out = [];
  for (var i = 0; i < roster.length; i++) {
    if (!roster[i].keepsDesk) continue;
    var deskId = roster[i].currentDesk;
    if (!deskId) continue;                     // roster bug; the Python validator catches it
    out.push({
      deskId: deskId,
      reason: (roster[i].name || roster[i].email) + ' is keeping this desk'
    });
  }
  return out;
}

/** Same information as a desk id -> reason map, for fast lookups. */
function lockedDeskMap_(roster) {
  var map = {};
  var locked = lockedDesks_(roster);
  for (var i = 0; i < locked.length; i++) map[locked[i].deskId] = locked[i].reason;
  return map;
}

/* ===========================================================================
 * 8. Small utilities
 * ======================================================================== */

/** One script property, or '' when properties are unreadable. Never throws. */
function prop_(name) {
  try {
    return String(PropertiesService.getScriptProperties().getProperty(name) || '');
  } catch (err) {
    return '';
  }
}

/** The signed-in user's email, or '' if Google will not tell us. Never throws. */
function activeEmail_() {
  try {
    var email = Session.getActiveUser().getEmail();
    return email ? normEmail_(email) : '';
  } catch (err) {
    return '';                                  // normal for out-of-domain visitors
  }
}

/** Build id recorded in every row: app version + config fingerprint. */
function clientVersion_() {
  return APP_NAME + '/' + APP_BUILD + '+' + safeCfg_('CONFIG_FINGERPRINT', 'unsynced');
}

/** {iso, passed} for the optional DEADLINE_ISO script property. */
function deadline_() {
  var iso = String(prop_(PROP_DEADLINE_ISO) || '').trim();
  if (!iso) return { iso: null, passed: false };
  var when = Date.parse(iso);
  if (isNaN(when)) {
    console.warn('Script property ' + PROP_DEADLINE_ISO + ' is not a parseable ISO-8601 ' +
      'instant ("' + iso + '"); ignoring it.');
    return { iso: null, passed: false };
  }
  return { iso: iso, passed: Date.now() > when };
}

/** Whether a signed-in user may submit under someone else's roster email. */
function proxySubmitAllowed_() {
  return String(prop_(PROP_ALLOW_PROXY) || '').trim().toLowerCase() === 'true';
}

/** Now, as ISO-8601 with a UTC offset, in the script's timezone (SPEC §3.1). */
function nowIso_() {
  var tz = Session.getScriptTimeZone() || 'America/Detroit';
  return Utilities.formatDate(new Date(), tz, "yyyy-MM-dd'T'HH:mm:ssXXX");
}

/** Sheet cells come back as Date objects when Sheets decided to parse them. */
function isoCell_(value) {
  if (value instanceof Date) {
    var tz = Session.getScriptTimeZone() || 'America/Detroit';
    return Utilities.formatDate(value, tz, "yyyy-MM-dd'T'HH:mm:ssXXX");
  }
  return String(value === undefined || value === null ? '' : value).trim();
}

function cell_(row, index) {
  if (index === undefined || index === null) return '';
  var v = row[index];
  return String(v === undefined || v === null ? '' : v).trim();
}

/** Case-insensitive column read from a roster row. */
function pick_(row, name) {
  var found = lookupAttribute_(row, name);
  return found.present ? found.value : '';
}

/** {present, value} for a case-insensitive attribute lookup. */
function lookupAttribute_(attrs, name) {
  if (!attrs || typeof attrs !== 'object') return { present: false, value: undefined };
  if (Object.prototype.hasOwnProperty.call(attrs, name)) {
    return { present: true, value: attrs[name] };
  }
  var wanted = String(name).trim().toLowerCase();
  var keys = Object.keys(attrs);
  for (var i = 0; i < keys.length; i++) {
    if (keys[i].trim().toLowerCase() === wanted) return { present: true, value: attrs[keys[i]] };
  }
  return { present: false, value: undefined };
}

/** The actual key an attribute lives under, so overrides do not duplicate it. */
function attributeKey_(attrs, name) {
  var wanted = String(name).trim().toLowerCase();
  var keys = Object.keys(attrs);
  for (var i = 0; i < keys.length; i++) {
    if (keys[i].trim().toLowerCase() === wanted) return keys[i];
  }
  return name;
}

/** SPEC §2.3: yes/no/true/false/1/0/y/n, case-insensitive. Blank is false. */
function truthy_(value) {
  if (value === true) return true;
  if (value === false || value === undefined || value === null) return false;
  if (typeof value === 'number') return value !== 0;
  var s = String(value).trim().toLowerCase();
  return s === 'yes' || s === 'y' || s === 'true' || s === 't' || s === '1';
}

/** A number if the value reads as one, else null. Used by range/scalar matchers. */
function toNumber_(value) {
  if (typeof value === 'number') return isFinite(value) ? value : null;
  if (typeof value === 'boolean' || value === null || value === undefined) return null;
  var s = String(value).trim();
  if (s === '' || !/^[+-]?(\d+(\.\d+)?|\.\d+)$/.test(s)) return null;
  var n = Number(s);
  return isFinite(n) ? n : null;
}

function normStr_(value) {
  return String(value === undefined || value === null ? '' : value).trim().toLowerCase();
}

function normEmail_(value) {
  return normStr_(value);
}

function intersect_(a, b) {
  var out = [];
  for (var i = 0; i < a.length; i++) {
    if (b.indexOf(a[i]) >= 0 && out.indexOf(a[i]) < 0) out.push(a[i]);
  }
  return out;
}

function isArray_(value) {
  return Object.prototype.toString.call(value) === '[object Array]';
}

/** Readable text out of anything that was thrown. */
function errText_(err) {
  if (!err) return 'Unknown error.';
  if (err.message) return String(err.message);
  return String(err);
}
