#!/usr/bin/env python3
"""Embed config/ into frontend/mock_server.html.

The mock server is the dev-only stand-in for google.script.run (see
frontend/DEPLOY.md). It has to answer getBootstrap() with the *real* rooms,
zones, eligibility rules and scoring curve, otherwise the UI gets built against
a fiction. Rather than copy those by hand, this script splices the config files
verbatim into the block delimited by

    /* BEGIN GENERATED by tools/embed_mock_config.py ... */
    ...
    /* END GENERATED */

Run it after editing anything in config/:

    python3 tools/embed_mock_config.py

It is idempotent and reads nothing but config/ and the target file. It does not
touch Apps Script sources that are actually deployed; ConfigData.gs is a
different file with a different generator (tools/sync_config.py).
"""

from __future__ import annotations

import json
import pathlib
import re
import sys

ROOT = pathlib.Path(__file__).resolve().parent.parent
CONFIG = ROOT / "config"
TARGET = ROOT / "frontend" / "mock_server.html"

BEGIN = "/* BEGIN GENERATED by tools/embed_mock_config.py — do not hand-edit */"
END = "/* END GENERATED */"

INDENT = "  "


def js_value(obj) -> str:
    """JSON is a subset of JS object-literal syntax, so this is a straight dump.

    Indented so the generated block stays diffable.
    """
    text = json.dumps(obj, indent=2, ensure_ascii=False)
    return text.replace("\n", "\n" + INDENT)


def js_string(text: str) -> str:
    return json.dumps(text, ensure_ascii=False)


def main() -> int:
    missing = [
        name
        for name in ("rooms.json", "eligibility.json", "scoring.json", "roster.csv")
        if not (CONFIG / name).exists()
    ]
    if missing:
        print(f"error: missing config file(s): {', '.join(missing)}", file=sys.stderr)
        return 1
    if not TARGET.exists():
        print(f"error: {TARGET} does not exist", file=sys.stderr)
        return 1

    rooms = json.loads((CONFIG / "rooms.json").read_text(encoding="utf-8"))
    eligibility = json.loads((CONFIG / "eligibility.json").read_text(encoding="utf-8"))
    scoring = json.loads((CONFIG / "scoring.json").read_text(encoding="utf-8"))
    roster_csv = (CONFIG / "roster.csv").read_text(encoding="utf-8")

    block = "\n".join(
        [
            BEGIN,
            f"{INDENT}var ROOMS = {js_value(rooms)};",
            f"{INDENT}var ELIGIBILITY = {js_value(eligibility)};",
            f"{INDENT}var SCORING = {js_value(scoring)};",
            f"{INDENT}var ROSTER_CSV = {js_string(roster_csv)};",
            f"{INDENT}{END}",
        ]
    )

    source = TARGET.read_text(encoding="utf-8")
    pattern = re.compile(
        re.escape(BEGIN) + r".*?" + re.escape(END),
        re.DOTALL,
    )
    if not pattern.search(source):
        print(
            f"error: could not find the generated block in {TARGET}.\n"
            f"       Expected a {BEGIN!r} ... {END!r} pair.",
            file=sys.stderr,
        )
        return 1

    # A function replacement is used deliberately: re.sub does not interpret
    # backslash escapes in the value a callable returns, and roster.csv is
    # embedded as a JS string literal full of \n.
    updated = pattern.sub(lambda _m: block, source, count=1)

    if updated == source:
        print(f"{TARGET.relative_to(ROOT)} already up to date")
        return 0

    TARGET.write_text(updated, encoding="utf-8")
    desks = sum(len(room.get("desks", [])) for room in rooms.get("rooms", []))
    curve = scoring["curves"][scoring["primary_curve"]]
    print(
        f"wrote {TARGET.relative_to(ROOT)}: "
        f"{len(rooms.get('rooms', []))} room(s), {desks} desks, "
        f"{len(rooms.get('zones', {}))} zones, K={len(curve)}, "
        f"{max(0, len(roster_csv.strip().splitlines()) - 1)} roster rows"
    )
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
